name: Terraform Check

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init
        working-directory: day5

      - name: Terraform Validate
        run: terraform validate
        working-directory: day5

      - name: Terraform Plan
        run: terraform plan
        working-directory: day5
